

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=5173
      - REACT_APP_TRANSLATION_URL=http://localhost:3000
    depends_on:
      - app

  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - TRANSLATION_URL=http://localhost:5001
    depends_on:
      - libretranslate

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5001:5000"
  
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  # test:
  #   build: 
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   command: npm run test
  #   volumes:
  #     - .:/app
  #   environment:
  #     - NODE_ENV=test
  #     - DATABASE_URI=mongodb://admin:password@mongo:27017/testDb?authSource=admin
  #     - LLM_API_URL=http://host.docker.internal:8080/llm/generate
  #   depends_on:
  #     - mongo
  #     - wiremock

# volumes:
#   mongo_data: